=== gmariotti/distributed-programming-II-assignments/assignment1/dtd/wfInfo.dtd
<!ELEMENT information (workflows, processes)>
    <!ELEMENT workflows (workflow*)>
    <!ELEMENT workflow (action+)>
    <!ATTLIST workflow
        name    ID          #REQUIRED
        >
    <!ELEMENT action (simpleAc|processAc)>
    <!ATTLIST action
        name    NMTOKEN         #REQUIRED
        role    NMTOKEN         #REQUIRED
        autins  (true|false)    #REQUIRED
        >
    <!ELEMENT simpleAc EMPTY>
    <!ATTLIST simpleAc
        next    NMTOKENS   #IMPLIED
        >
    <!ELEMENT processAc EMPTY>
    <!ATTLIST processAc
        workflow    IDREF   #REQUIRED
        >

    <!-- if status is present, than somebody has taken it in charge -->
    <!ELEMENT processes (process*)>
    <!ELEMENT process (starttime, status+)>
    <!ATTLIST process
        workflow    IDREF   #REQUIRED
        >

    <!-- if endtime is present, than it means the action is terminated -->
    <!ELEMENT status (endtime?)>
    <!ATTLIST status
        action  NMTOKEN       #REQUIRED
        actor   NMTOKENS      #IMPLIED
        >
    <!ELEMENT endtime (#PCDATA)>
    <!ELEMENT starttime (#PCDATA)>

=== gmariotti/distributed-programming-II-assignments/assignment1/dtd/wfInfo.xml
<?xml version="1.0"?>
<!DOCTYPE information SYSTEM "wfInfo.dtd">
<information>
    <workflows>
        <workflow name="NormalSale">
            <action name="GoodsDelivery" role="Warehouseman" autins="true">
                <simpleAc/>
            </action>
            <action name="InvoiceIssuance" role="AccountingMan" autins="true">
                <simpleAc next="PaymentRec"/>
            </action>
            <action name="PaymentRec" role="AccountingMan" autins="false">
                <simpleAc/>
            </action>
        </workflow>

        <workflow name="SaleManagement">
            <action name="PrepaidSale" role="Salesman" autins="true">
                <processAc workflow="NormalSale"/>
            </action>
            <action name="NormalSale" role="SalesManager" autins="true">
                <simpleAc/>
            </action>
        </workflow>
    </workflows>

    <processes>
        <process workflow="SaleManagement">
            <starttime>17/10/2015T22:01zCEST</starttime>
            <status action="PrepaidSale" actor="Actor1">
                <endtime>17/10/2015T22:01zCEST </endtime>
            </status>
            <status action="NormalSale" actor="Actor2"/>
        </process>

        <process workflow="NormalSale">
            <starttime>17/10/2015T22:01zCEST</starttime>
            <status action="GoodsDelivery" actor="Actor3">
                <endtime>17/10/2015T22:01zCEST </endtime>
            </status>
            <status action="InvoiceIssuance" actor="Actor4">
                <endtime>17/10/2015T22:01zCEST</endtime>
            </status>
            <status action="PaymentRec"/>
        </process>
    </processes>
</information>
